language: node_js
node_js:
  - 16.5.0

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend smsrinivas781981/udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push smsrinivas781981/udagram-frontend